apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncscribe-client
  namespace: syncscribe
  annotations:
    kubernetes.io/ingress.global-static-ip-name: syncscribe-ip
    networking.gke.io/managed-certificates: syncscribe-cert
spec:
  ingressClassName: gce
  rules:
    - host: 34-144-248-122.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncscribe-client
                port:
                  number: 80